### ISSUE TITLE
I  seem to have an error in a specific block of code please fix it for me 

### ISSUE THREAD

**Issue by Ibrahxm** [Ibrahxm/SQAStudebt20f20718#1]
import java.util.Scanner;

public class Main {
  public static void main(String[] args) {
    Scanner scan = new Scanner(System.in);
    System.out.println("Enter a number: ");
    int num = scan.nextInt();

    for (int i = 0; i < num; i++) {
      System.out.println(i);
    }

    if (num > 0) {
      System.out.println("The number is positive.");
    } else if (num < 0) {
      System.out.println("The number is negative.");
    } else {
      System.out.println("The number is zero.");
    }
  }
}

**Comment by dex1670** [comment]
import java.util.Scanner;

public class Main {
  public static void main(String[] args) {
    Scanner scan = new Scanner(System.in);
    System.out.println("Enter a number: ");
    int num = scan.nextInt();

    for (int i = 0; i < num; i++) {
      System.out.println(i);
    }

    if (num >= 0) {
      System.out.println("The number is positive or zero.");
    } else {
      System.out.println("The number is negative.");
    }
  }
}
